import type { Lecture } from '@/interfaces/_lecturesInterfaces.js'
import { penguinImageUrl } from '../../../constants/imageUrls.js'
import { lectureUrl } from '../../../constants/linkUrls.js'

const dummyLectures: Lecture[] = [
  {
    uuid: '550e8400-e29b-41d4-a716-446655440000',
    title: 'Django 완벽 가이드',
    instructor: '홍길동',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 1,
        name: '백엔드',
      },
      {
        id: 5,
        name: 'Django',
      },
    ],
    difficulty: 'NORMAL',
    original_price: 100000,
    discount_price: 50000,
    platform: 'inflearn',
    average_rating: 4.75,
    duration: 600,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440001',
    title: 'React 마스터클래스',
    instructor: '김민수',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 2,
        name: '프론트엔드',
      },
      {
        id: 6,
        name: 'React',
      },
    ],
    difficulty: 'HARD',
    original_price: 150000,
    discount_price: 90000,
    platform: 'udemy',
    average_rating: 4.9,
    duration: 720,
    url_link: lectureUrl,
    is_bookmarked: true,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440002',
    title: 'Python 기초부터 실무까지',
    instructor: '박지영',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 3,
        name: '프로그래밍',
      },
      {
        id: 7,
        name: 'Python',
      },
    ],
    difficulty: 'EASY',
    original_price: 80000,
    discount_price: 40000,
    platform: 'inflearn',
    average_rating: 4.6,
    duration: 480,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440003',
    title: 'Vue.js 실전 프로젝트',
    instructor: '이승훈',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 2,
        name: '프론트엔드',
      },
      {
        id: 8,
        name: 'Vue.js',
      },
    ],
    difficulty: 'NORMAL',
    original_price: 120000,
    discount_price: 70000,
    platform: 'inflearn',
    average_rating: 4.8,
    duration: 540,
    url_link: lectureUrl,
    is_bookmarked: true,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440004',
    title: 'Node.js 백엔드 개발',
    instructor: '최윤석',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 1,
        name: '백엔드',
      },
      {
        id: 9,
        name: 'Node.js',
      },
    ],
    difficulty: 'NORMAL',
    original_price: 110000,
    discount_price: 60000,
    platform: 'inflearn',
    average_rating: 4.7,
    duration: 660,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440005',
    title: 'Angular 완벽 가이드',
    instructor: '정소라',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 2,
        name: '프론트엔드',
      },
      {
        id: 10,
        name: 'Angular',
      },
    ],
    difficulty: 'HARD',
    original_price: 140000,
    discount_price: 80000,
    platform: 'udemy',
    average_rating: 4.5,
    duration: 780,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440006',
    title: 'MySQL 데이터베이스 설계',
    instructor: '강태준',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 4,
        name: '데이터베이스',
      },
      {
        id: 11,
        name: 'MySQL',
      },
    ],
    difficulty: 'NORMAL',
    original_price: 90000,
    discount_price: 45000,
    platform: 'inflearn',
    average_rating: 4.4,
    duration: 420,
    url_link: lectureUrl,
    is_bookmarked: true,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440007',
    title: 'JavaScript ES6+ 최신 문법',
    instructor: '한수진',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 3,
        name: '프로그래밍',
      },
      {
        id: 12,
        name: 'JavaScript',
      },
    ],
    difficulty: 'EASY',
    original_price: 70000,
    discount_price: 35000,
    platform: 'inflearn',
    average_rating: 4.8,
    duration: 360,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440008',
    title: 'Spring Boot 실무 프로젝트',
    instructor: '오민철',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 1,
        name: '백엔드',
      },
      {
        id: 13,
        name: 'Spring',
      },
    ],
    difficulty: 'HARD',
    original_price: 160000,
    discount_price: 100000,
    platform: 'inflearn',
    average_rating: 4.9,
    duration: 840,
    url_link: lectureUrl,
    is_bookmarked: true,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440009',
    title: 'TypeScript 완벽 정복',
    instructor: '임가영',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 3,
        name: '프로그래밍',
      },
      {
        id: 14,
        name: 'TypeScript',
      },
    ],
    difficulty: 'NORMAL',
    original_price: 130000,
    discount_price: 75000,
    platform: 'udemy',
    average_rating: 4.7,
    duration: 600,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440010',
    title: 'MongoDB 기초부터 심화까지',
    instructor: '윤호진',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 4,
        name: '데이터베이스',
      },
      {
        id: 15,
        name: 'MongoDB',
      },
    ],
    difficulty: 'NORMAL',
    original_price: 100000,
    discount_price: 55000,
    platform: 'inflearn',
    average_rating: 4.6,
    duration: 510,
    url_link: lectureUrl,
    is_bookmarked: true,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440011',
    title: 'AWS 클라우드 아키텍처',
    instructor: '서다혜',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 16,
        name: '클라우드',
      },
      {
        id: 17,
        name: 'AWS',
      },
    ],
    difficulty: 'HARD',
    original_price: 200000,
    discount_price: 120000,
    platform: 'inflearn',
    average_rating: 4.8,
    duration: 900,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440012',
    title: 'Docker 컨테이너 기술',
    instructor: '남궁민',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 18,
        name: 'DevOps',
      },
      {
        id: 19,
        name: 'Docker',
      },
    ],
    difficulty: 'NORMAL',
    original_price: 115000,
    discount_price: 65000,
    platform: 'udemy',
    average_rating: 4.5,
    duration: 480,
    url_link: lectureUrl,
    is_bookmarked: true,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440013',
    title: 'Git & GitHub 완벽 가이드',
    instructor: '조은서',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 20,
        name: '협업툴',
      },
      {
        id: 21,
        name: 'Git',
      },
    ],
    difficulty: 'EASY',
    original_price: 60000,
    discount_price: 30000,
    platform: 'inflearn',
    average_rating: 4.9,
    duration: 300,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440014',
    title: 'Redux 상태관리 마스터',
    instructor: '배현우',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 2,
        name: '프론트엔드',
      },
      {
        id: 22,
        name: 'Redux',
      },
    ],
    difficulty: 'HARD',
    original_price: 135000,
    discount_price: 85000,
    platform: 'udemy',
    average_rating: 4.6,
    duration: 630,
    url_link: lectureUrl,
    is_bookmarked: true,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440015',
    title: 'PostgreSQL 실무 활용',
    instructor: '신혜린',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 4,
        name: '데이터베이스',
      },
      {
        id: 23,
        name: 'PostgreSQL',
      },
    ],
    difficulty: 'NORMAL',
    original_price: 95000,
    discount_price: 50000,
    platform: 'inflearn',
    average_rating: 4.7,
    duration: 540,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440016',
    title: 'Kubernetes 오케스트레이션',
    instructor: '황준호',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 18,
        name: 'DevOps',
      },
      {
        id: 24,
        name: 'Kubernetes',
      },
    ],
    difficulty: 'HARD',
    original_price: 180000,
    discount_price: 110000,
    platform: 'udemy',
    average_rating: 4.4,
    duration: 720,
    url_link: lectureUrl,
    is_bookmarked: true,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440017',
    title: 'Flutter 모바일 앱 개발',
    instructor: '김나연',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 25,
        name: '모바일',
      },
      {
        id: 26,
        name: 'Flutter',
      },
    ],
    difficulty: 'NORMAL',
    original_price: 125000,
    discount_price: 70000,
    platform: 'udemy',
    average_rating: 4.8,
    duration: 660,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440018',
    title: 'GraphQL API 설계와 구현',
    instructor: '이동현',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 1,
        name: '백엔드',
      },
      {
        id: 27,
        name: 'GraphQL',
      },
    ],
    difficulty: 'HARD',
    original_price: 145000,
    discount_price: 90000,
    platform: 'udemy',
    average_rating: 4.5,
    duration: 600,
    url_link: lectureUrl,
    is_bookmarked: true,
  },
  {
    uuid: '550e8400-e29b-41d4-a716-446655440019',
    title: 'Next.js 풀스택 개발',
    instructor: '안수빈',
    thumbnail_img_url: penguinImageUrl,
    categories: [
      {
        id: 2,
        name: '프론트엔드',
      },
      {
        id: 28,
        name: 'Next.js',
      },
    ],
    difficulty: 'HARD',
    original_price: 170000,
    discount_price: 105000,
    platform: 'udemy',
    average_rating: 4.9,
    duration: 780,
    url_link: lectureUrl,
    is_bookmarked: false,
  },
]

export default dummyLectures
