import type { Applicant } from '../../../interfaces/index.js'

export const dummyApplicantArray: Applicant[] = [
  {
    id: 12,
    application: {
      nickname: 'dev_juwon',
      gender: '남성',
      profile_image: 'https://cdn.example.com/profiles/juwon.png',
    },
    available_time: '평일 저녁, 주말 오전',
    has_study_experience: true,
    status: 'pending',
    created_at: '2025-10-16 11:25',
  },
  {
    id: 13,
    application: {
      nickname: 'frontend_park',
      gender: '여성',
      profile_image: null,
    },
    available_time: '주중 오후',
    has_study_experience: false,
    status: 'accepted',
    created_at: '2025-10-15 19:48',
  },
  {
    id: 14,
    application: {
      nickname: 'js_kim',
      gender: '남성',
      profile_image: 'https://cdn.example.com/profiles/js_kim.jpg',
    },
    available_time: '주말 전일',
    has_study_experience: true,
    status: 'rejected',
    created_at: '2025-10-14 10:32',
  },
  {
    id: 15,
    application: {
      nickname: 'react_sujin',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/sujin.png',
    },
    available_time: '평일 오후 7시 이후',
    has_study_experience: true,
    status: 'pending',
    created_at: '2025-10-18 21:05',
  },
  {
    id: 16,
    application: {
      nickname: 'backend_lee',
      gender: '남성',
      profile_image: null,
    },
    available_time: '주말 오후',
    has_study_experience: false,
    status: 'accepted',
    created_at: '2025-10-12 14:44',
  },
  {
    id: 17,
    application: {
      nickname: 'uiux_haeun',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/haeun.jpg',
    },
    available_time: '평일 오전',
    has_study_experience: true,
    status: 'pending',
    created_at: '2025-10-20 09:18',
  },
  {
    id: 18,
    application: {
      nickname: 'node_min',
      gender: '남성',
      profile_image: 'https://cdn.example.com/profiles/min.png',
    },
    available_time: '주중 저녁, 주말 오후',
    has_study_experience: false,
    status: 'rejected',
    created_at: '2025-10-11 17:55',
  },
  {
    id: 19,
    application: {
      nickname: 'design_jina',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'accepted',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 20,
    application: {
      nickname: 'design_jina',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'accepted',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 21,
    application: {
      nickname: 'design_jina',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'accepted',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 22,
    application: {
      nickname: 'design_jina',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'accepted',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 23,
    application: {
      nickname: 'design_jina',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'accepted',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 24,
    application: {
      nickname: 'design_jina',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'accepted',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 25,
    application: {
      nickname: 'design_jina',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'accepted',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 26,
    application: {
      nickname: 'design_jina',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'accepted',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 27,
    application: {
      nickname: 'design_jina',
      gender: '여성',
      profile_image: 'https://cdn.example.com/profiles/jina.png',
    },
    available_time: '평일 오후, 주말 오전',
    has_study_experience: true,
    status: 'accepted',
    created_at: '2025-10-19 15:37',
  },
]
