import type { ApplicantDetail } from '@/interfaces/_applicantDetailInterface.js'

export const dummyApplicantDetail: ApplicantDetail[] = [
  {
    id: 12,
    nickname: '홍길동',
    profile_image: 'https://cdn.example.com/profiles/juwon.png',
    introduction:
      '안녕하세요! 프론트엔드 개발을 배우고 있는 홍길동입니다. 현재 React를 활용한 프로젝트를 진행하고 있으며, Unity를 통한 게임 개발에 관심이 생겨 지원했습니다.',
    motivation:
      'Unity 게임 개발을 통해 새로운 영역에 도전하고 싶습니다. 특히 3D 게임 개발 경험을 쌓고 향후 게임 개발자로 전향하는 것이 목표입니다.',
    goal: '3개월 후에는 Unity를 활용한 완성도 높은 3D 게임을 개발할 수 있는 능력을 갖추고 싶습니다.',
    available_times: ['월 18:00-20:00', '수 19:00-21:00'],
    has_study_experience: true,
    study_experience_detail:
      '작년에 React 스터디를 6개월간 진행했으며, 팀 프로젝트로 쇼핑몰 웹사이트를 완성했습니다.',
    status: 'PENDING',
    created_at: '2024-11-25 14:30',
    gender: '남성',
  },
  {
    id: 13,
    nickname: 'frontend_park',
    gender: '여성',
    profile_image: 'https://cdn.example.com/profiles/juwon.png',
    introduction:
      '안녕하세요! 프론트엔드 개발을 배우고 있는 홍길동입니다. 현재 React를 활용한 프로젝트를 진행하고 있으며, Unity를 통한 게임 개발에 관심이 생겨 지원했습니다.',
    motivation:
      'Unity 게임 개발을 통해 새로운 영역에 도전하고 싶습니다. 특히 3D 게임 개발 경험을 쌓고 향후 게임 개발자로 전향하는 것이 목표입니다.',
    goal: '3개월 후에는 Unity를 활용한 완성도 높은 3D 게임을 개발할 수 있는 능력을 갖추고 싶습니다.',
    available_times: ['월 18:00-20:00', '수 19:00-21:00'],
    has_study_experience: false,
    study_experience_detail:
      '작년에 React 스터디를 6개월간 진행했으며, 팀 프로젝트로 쇼핑몰 웹사이트를 완성했습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-15 19:48',
  },
  {
    id: 14,
    nickname: 'js_kim',
    gender: '남성',
    profile_image: 'https://cdn.example.com/profiles/js_kim.jpg',
    introduction: '안녕하세요, 프론트엔드 개발을 공부하고 있는 김지수입니다.',
    motivation:
      '자바스크립트 실력을 팀 프로젝트를 통해 더 끌어올리고 싶습니다.',
    goal: '실무와 비슷한 협업 경험을 쌓고 싶습니다.',
    available_times: ['토요일 오전', '일요일 오후'],
    has_study_experience: true,
    study_experience_detail:
      '부트캠프에서 3개월 동안 React 중심의 스터디를 진행했습니다.',
    status: 'REJECTED',
    created_at: '2025-10-14 10:32',
  },
  {
    id: 15,
    nickname: 'react_sujin',
    gender: '여성',
    profile_image: 'https://cdn.example.com/profiles/sujin.png',
    introduction: 'React로 웹 개발을 배우고 있는 수진입니다.',
    motivation: '실제 프로젝트를 통해 컴포넌트 설계 감각을 익히고 싶습니다.',
    goal: '프론트엔드 실력을 탄탄하게 쌓아 포트폴리오를 완성하는 것이 목표입니다.',
    available_times: ['평일 오후 7시 이후'],
    has_study_experience: true,
    study_experience_detail:
      '토이 프로젝트 중심의 스터디에 참여해 본 경험이 있습니다.',
    status: 'PENDING',
    created_at: '2025-10-18 21:05',
  },
  {
    id: 16,
    nickname: 'backend_lee',
    gender: '남성',
    profile_image: 'https://cdn.example.com/profiles/sujin.png',
    introduction:
      'Node.js와 Express를 공부하고 있는 백엔드 개발자 지망생입니다.',
    motivation: '프론트엔드와 협업하면서 API 설계 감각을 키우고 싶습니다.',
    goal: 'RESTful API 설계와 서버 구조를 학습하고 싶습니다.',
    available_times: ['주말 오후'],
    has_study_experience: false,
    study_experience_detail: '',
    status: 'ACCEPTED',
    created_at: '2025-10-12 14:44',
  },
  {
    id: 17,
    nickname: 'uiux_haeun',
    gender: '여성',
    profile_image: 'https://cdn.example.com/profiles/haeun.jpg',
    introduction: 'UI/UX 디자인에 관심이 많은 학생입니다.',
    motivation: '디자인과 개발의 경계를 이해하고 싶습니다.',
    goal: '실제 사용자 경험을 고려한 디자인을 개발로 구현해보고 싶습니다.',
    available_times: ['평일 오전'],
    has_study_experience: true,
    study_experience_detail:
      '디자인 툴 스터디를 통해 피그마 협업 경험이 있습니다.',
    status: 'PENDING',
    created_at: '2025-10-20 09:18',
  },
  {
    id: 18,
    nickname: 'node_min',
    gender: '남성',
    profile_image: 'https://cdn.example.com/profiles/min.png',
    introduction: 'Node.js 백엔드에 관심 있는 대학생입니다.',
    motivation: '실제 서버 구축과 데이터 연동 과정을 배우고 싶습니다.',
    goal: 'TypeScript 기반 백엔드 프로젝트 경험을 쌓는 것이 목표입니다.',
    available_times: ['주중 저녁', '주말 오후'],
    has_study_experience: false,
    study_experience_detail: '',
    status: 'REJECTED',
    created_at: '2025-10-11 17:55',
  },
  {
    id: 19,
    nickname: 'design_jina',
    gender: '여성',
    profile_image: 'https://cdn.example.com/profiles/jina.png',
    introduction: '디자인과 프론트엔드를 함께 배우고 있는 진아입니다.',
    motivation:
      'UI 구현을 통해 디자인이 어떻게 코드로 옮겨지는지 배우고 싶습니다.',
    goal: '디자이너와 개발자의 협업 과정을 직접 경험해보고 싶습니다.',
    available_times: ['평일 오후', '주말 오전'],
    has_study_experience: true,
    study_experience_detail: '디자인 툴 기반의 프로젝트 경험이 있습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 20,
    nickname: 'data_sangho',
    gender: '남성',
    profile_image: 'https://cdn.example.com/profiles/sangho.jpg',
    introduction: '데이터 분석과 시각화에 관심이 많습니다.',
    motivation: '데이터를 기반으로 한 프로젝트에 참여하고 싶습니다.',
    goal: '프론트엔드에서 데이터를 효과적으로 보여주는 법을 배우고 싶습니다.',
    available_times: ['토요일 오후', '일요일 오후'],
    has_study_experience: true,
    study_experience_detail:
      '대학 프로젝트에서 Python으로 데이터 분석 경험이 있습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 21,
    nickname: 'pm_han',
    gender: '여성',
    profile_image: 'https://cdn.example.com/profiles/han.jpg',
    introduction: '프로덕트 매니징과 협업 커뮤니케이션에 관심이 있습니다.',
    motivation: '프로젝트 진행 프로세스를 직접 체험해보고 싶습니다.',
    goal: '기획과 개발 간의 협업 방식을 배우는 것이 목표입니다.',
    available_times: ['평일 오후', '주말 오전'],
    has_study_experience: true,
    study_experience_detail: '기획자와 개발자가 함께한 해커톤에 참여했습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 22,
    nickname: 'seo_dev',
    gender: '남성',
    profile_image: 'https://cdn.example.com/profiles/seodev.png',
    introduction: 'Next.js와 SEO 최적화에 관심이 있습니다.',
    motivation:
      'SEO 성능 개선을 실습하며 프론트엔드의 깊은 부분을 이해하고 싶습니다.',
    goal: 'SSR과 CSR의 차이를 명확히 이해하고 싶습니다.',
    available_times: ['주중 저녁', '주말 오전'],
    has_study_experience: true,
    study_experience_detail: 'Next.js 개인 블로그를 만들어본 경험이 있습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 23,
    nickname: 'cloud_yun',
    gender: '남성',
    profile_image: 'https://cdn.example.com/profiles/yun.png',
    introduction: 'AWS와 클라우드 인프라에 관심이 많습니다.',
    motivation: '배포 환경을 직접 구성하고 유지보수하는 법을 배우고 싶습니다.',
    goal: 'CI/CD 파이프라인을 실제로 구축해보는 것이 목표입니다.',
    available_times: ['토요일 오전', '일요일 오전'],
    has_study_experience: true,
    study_experience_detail: 'AWS EC2를 이용해 서버 배포 경험이 있습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 24,
    nickname: 'ai_harin',
    gender: '여성',
    profile_image: 'https://cdn.example.com/profiles/harin.jpg',
    introduction: 'AI 모델과 웹 연동에 흥미가 있습니다.',
    motivation: '웹에서 머신러닝 모델을 서비스하는 경험을 해보고 싶습니다.',
    goal: 'TensorFlow.js를 이용한 간단한 모델 실습을 목표로 합니다.',
    available_times: ['평일 오후', '주말 오전'],
    has_study_experience: true,
    study_experience_detail: 'AI 스터디에서 기초 신경망 모델을 구현했습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 25,
    nickname: 'test_dev',
    gender: '남성',
    profile_image: 'https://cdn.example.com/profiles/testdev.png',
    introduction: '테스트 자동화와 품질 관리에 관심이 많습니다.',
    motivation: 'CI 환경에서 테스트가 자동화되는 과정을 배우고 싶습니다.',
    goal: 'Jest와 Cypress를 활용한 테스트 코드를 작성하고 싶습니다.',
    available_times: ['평일 오후', '주말 오전'],
    has_study_experience: true,
    study_experience_detail:
      '테스트 코드 스터디에서 React 컴포넌트 테스트 경험이 있습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 26,
    nickname: 'infra_yujin',
    gender: '여성',
    profile_image: 'https://cdn.example.com/profiles/yujin.png',
    introduction: '인프라와 배포 환경 자동화에 관심이 있습니다.',
    motivation: '실무처럼 협업 환경을 만들어보고 싶습니다.',
    goal: 'Docker와 GitHub Actions를 이용해 자동 배포 파이프라인을 구축하고 싶습니다.',
    available_times: ['평일 오후', '주말 오전'],
    has_study_experience: true,
    study_experience_detail: 'Docker 기반 배포 환경 구축 경험이 있습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-19 15:37',
  },
  {
    id: 27,
    nickname: 'python_dongha',
    gender: '남성',
    profile_image: 'https://cdn.example.com/profiles/dongha.png',
    introduction:
      '파이썬으로 데이터 분석과 간단한 웹 서버를 만들어본 경험이 있습니다.',
    motivation: '풀스택 관점에서 프로젝트 구조를 이해하고 싶습니다.',
    goal: '프론트와 백엔드 통합 프로젝트를 경험해보고 싶습니다.',
    available_times: ['주말 오전', '주말 오후'],
    has_study_experience: true,
    study_experience_detail: '대학에서 Flask 기반 팀 프로젝트 경험이 있습니다.',
    status: 'ACCEPTED',
    created_at: '2025-10-19 15:37',
  },
]
