import type { ChatRoomListItem } from '@/interfaces/_chatInterfaces.js'

export const dummyChatRoomArray: ChatRoomListItem[] = [
  {
    uuid: '201',
    name: '리눅스 스터디',
    unread_message_count: 1,
    last_message_sender_nickname: '홍길동',
    last_message_content: '오늘 스터디 7시에 시작합니다.',
    created_at: '2025-10-15T10:30:00Z',
  },
  {
    uuid: '202',
    name: 'React 프로젝트',
    unread_message_count: 0,
    last_message_sender_nickname: '김철수',
    last_message_content: '네, 알겠습니다!',
    created_at: '2025-10-15T10:31:00Z',
  },
  {
    uuid: '203',
    name: 'TypeScript 심화',
    unread_message_count: 5,
    last_message_sender_nickname: '박영희',
    last_message_content: '혹시 궁금한 점 있으신가요?',
    created_at: '2025-10-15T10:32:00Z',
  },
  {
    uuid: '204',
    name: 'Node.js 백엔드',
    unread_message_count: 0,
    last_message_sender_nickname: '이민수',
    last_message_content: '아직은 없습니다. 곧 도착합니다.',
    created_at: '2025-10-15T10:33:00Z',
  },
  {
    uuid: '205',
    name: '클라우드 컴퓨팅',
    unread_message_count: 12,
    last_message_sender_nickname: '최지영',
    last_message_content: '네, 조심히 오세요!',
    created_at: '2025-10-15T10:34:00Z',
  },
  {
    uuid: '206',
    name: 'Git & GitHub',
    unread_message_count: 0,
    last_message_sender_nickname: '강현우',
    last_message_content: '도착했습니다!',
    created_at: '2025-10-15T10:35:00Z',
  },
  {
    uuid: '207',
    name: '데이터베이스 설계',
    unread_message_count: 3,
    last_message_sender_nickname: '윤서진',
    last_message_content: '그럼 시작할까요?',
    created_at: '2025-10-15T10:36:00Z',
  },
  {
    uuid: '208',
    name: '알고리즘 문제풀이',
    unread_message_count: 0,
    last_message_sender_nickname: '정우진',
    last_message_content: '네 좋습니다.',
    created_at: '2025-10-15T10:37:00Z',
  },
  {
    uuid: '209',
    name: 'UI/UX 디자인',
    unread_message_count: 7,
    last_message_sender_nickname: '한지민',
    last_message_content: '오늘 주제는 React Hooks입니다.',
    created_at: '2025-10-15T10:38:00Z',
  },
  {
    uuid: '210',
    name: '모바일 앱 개발',
    unread_message_count: 0,
    last_message_sender_nickname: '신동현',
    last_message_content: '네, 기대됩니다!',
    created_at: '2025-10-15T10:39:00Z',
  },
  {
    uuid: '211',
    name: 'DevOps 자동화',
    unread_message_count: 1,
    last_message_sender_nickname: '오수민',
    last_message_content: 'useEffect 사용 시 주의할 점은 무엇일까요?',
    created_at: '2025-10-15T10:40:00Z',
  },
  {
    uuid: '212',
    name: '인공지능 기초',
    unread_message_count: 0,
    last_message_sender_nickname: '구하준',
    last_message_content: '의존성 배열을 잘 관리해야겠죠.',
    created_at: '2025-10-15T10:41:00Z',
  },
  {
    uuid: '213',
    name: '프론트엔드 성능',
    unread_message_count: 2,
    last_message_sender_nickname: '남지아',
    last_message_content: '맞습니다. 클린업 함수도 중요하고요.',
    created_at: '2025-10-15T10:42:00Z',
  },
  {
    uuid: '214',
    name: '백엔드 보안',
    unread_message_count: 0,
    last_message_sender_nickname: '류준서',
    last_message_content: 'useCallback, useMemo도 함께 사용하면 좋죠.',
    created_at: '2025-10-15T10:43:00Z',
  },
  {
    uuid: '215',
    name: '데이터 분석',
    unread_message_count: 9,
    last_message_sender_nickname: '문예린',
    last_message_content: '네, 성능 최적화에 도움이 됩니다.',
    created_at: '2025-10-15T10:44:00Z',
  },
  {
    uuid: '216',
    name: '머신러닝 응용',
    unread_message_count: 0,
    last_message_sender_nickname: '박서준',
    last_message_content: 'Zustand로 상태 관리하는 것도 편하더라고요.',
    created_at: '2025-10-15T10:45:00Z',
  },
  {
    uuid: '217',
    name: '블록체인 기초',
    unread_message_count: 4,
    last_message_sender_nickname: '서하윤',
    last_message_content:
      '맞아요. TanStack Query도 비동기 데이터 관리에 최고죠.',
    created_at: '2025-10-15T10:46:00Z',
  },
  {
    uuid: '218',
    name: '게임 개발 입문',
    unread_message_count: 0,
    last_message_sender_nickname: '유지호',
    last_message_content: '네, 캐싱 기능이 정말 유용합니다.',
    created_at: '2025-10-15T10:47:00Z',
  },
  {
    uuid: '219',
    name: '클린 코드 실천',
    unread_message_count: 11,
    last_message_sender_nickname: '이도윤',
    last_message_content: '오늘 스터디 내용 정말 유익했습니다.',
    created_at: '2025-10-15T10:48:00Z',
  },
  {
    uuid: '220',
    name: '테스팅 전략',
    unread_message_count: 0,
    last_message_sender_nickname: '장예원',
    last_message_content: '저도요! 감사합니다.',
    created_at: '2025-10-15T10:49:00Z',
  },
  {
    uuid: '221',
    name: '애자일 방법론',
    unread_message_count: 6,
    last_message_sender_nickname: '전하은',
    last_message_content: '다음 주 주제는 무엇으로 할까요?',
    created_at: '2025-10-15T10:50:00Z',
  },
  {
    uuid: '222',
    name: '스크럼 마스터',
    unread_message_count: 0,
    last_message_sender_nickname: '조민준',
    last_message_content: '음... Next.js 어떠세요?',
    created_at: '2025-10-15T10:51:00Z',
  },
  {
    uuid: '223',
    name: '프로젝트 관리 툴',
    unread_message_count: 1,
    last_message_sender_nickname: '차은우',
    last_message_content:
      '좋은 생각입니다! Next.js로 SSR/SSG에 대해 다뤄볼까요?',
    created_at: '2025-10-15T10:52:00Z',
  },
  {
    uuid: '224',
    name: '커뮤니케이션 스킬',
    unread_message_count: 0,
    last_message_sender_nickname: '하윤서',
    last_message_content: '네, 그렇게 하면 좋을 것 같아요.',
    created_at: '2025-10-15T10:53:00Z',
  },
  {
    uuid: '225',
    name: '리더십 개발',
    unread_message_count: 8,
    last_message_sender_nickname: '홍지훈',
    last_message_content: '그럼 다음 주에 뵙겠습니다!',
    created_at: '2025-10-15T10:54:00Z',
  },
  {
    uuid: '226',
    name: '문제 해결 능력',
    unread_message_count: 0,
    last_message_sender_nickname: '황채원',
    last_message_content: '수고하셨습니다!',
    created_at: '2025-10-15T10:55:00Z',
  },
  {
    uuid: '227',
    name: '비판적 사고 훈련',
    unread_message_count: 2,
    last_message_sender_nickname: '김도현',
    last_message_content: '수고하셨습니다!',
    created_at: '2025-10-15T10:56:00Z',
  },
  {
    uuid: '228',
    name: '팀워크 향상',
    unread_message_count: 0,
    last_message_sender_nickname: '홍길동',
    last_message_content: '오늘 저녁은 뭐 드세요?',
    created_at: '2025-10-15T10:57:00Z',
  },
  {
    uuid: '229',
    name: '프론트엔드 아키텍처',
    unread_message_count: 15,
    last_message_sender_nickname: '김철수',
    last_message_content: '저는 치킨 먹으려고요!',
    created_at: '2025-10-15T10:58:00Z',
  },
  {
    uuid: '230',
    name: '백엔드 아키텍처',
    unread_message_count: 0,
    last_message_sender_nickname: '홍길동',
    last_message_content: '오 저도 치킨 좋아하는데!',
    created_at: '2025-10-15T10:59:00Z',
  },
  {
    uuid: '231',
    name: '데이터베이스 최적화',
    unread_message_count: 3,
    last_message_sender_nickname: '김철수',
    last_message_content: '같이 드실래요?',
    created_at: '2025-10-15T11:00:00Z',
  },
  {
    uuid: '232',
    name: '클라우드 보안',
    unread_message_count: 0,
    last_message_sender_nickname: '홍길동',
    last_message_content: '좋아요! 어디서 만날까요?',
    created_at: '2025-10-15T11:01:00Z',
  },
]
