import type { ChatRoomListItem } from '@/interfaces/_chatInterfaces.js'

export const dummyChatRoomArray: ChatRoomListItem[] = [
  {
    id: 201,
    study_name: '리눅스 스터디',
    sender_id: 5,
    message_counter: 1,
    sender_nickname: '홍길동',
    study_group_id: 100,
    content: '오늘 스터디 7시에 시작합니다.',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:30:00Z',
  },
  {
    id: 202,
    study_name: 'React 프로젝트',
    sender_id: 6,
    message_counter: 0,
    sender_nickname: '김철수',
    study_group_id: 101,
    content: '네, 알겠습니다!',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:31:00Z',
  },
  {
    id: 203,
    study_name: 'TypeScript 심화',
    sender_id: 5,
    message_counter: 5,
    sender_nickname: '박영희',
    study_group_id: 102,
    content: '혹시 궁금한 점 있으신가요?',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:32:00Z',
  },
  {
    id: 204,
    study_name: 'Node.js 백엔드',
    sender_id: 7,
    message_counter: 0,
    sender_nickname: '이민수',
    study_group_id: 103,
    content: '아직은 없습니다. 곧 도착합니다.',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:33:00Z',
  },
  {
    id: 205,
    study_name: '클라우드 컴퓨팅',
    sender_id: 8,
    message_counter: 12,
    sender_nickname: '최지영',
    study_group_id: 104,
    content: '네, 조심히 오세요!',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:34:00Z',
  },
  {
    id: 206,
    study_name: 'Git & GitHub',
    sender_id: 9,
    message_counter: 0,
    sender_nickname: '강현우',
    study_group_id: 105,
    content: '도착했습니다!',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:35:00Z',
  },
  {
    id: 207,
    study_name: '데이터베이스 설계',
    sender_id: 10,
    message_counter: 3,
    sender_nickname: '윤서진',
    study_group_id: 106,
    content: '그럼 시작할까요?',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:36:00Z',
  },
  {
    id: 208,
    study_name: '알고리즘 문제풀이',
    sender_id: 11,
    message_counter: 0,
    sender_nickname: '정우진',
    study_group_id: 107,
    content: '네 좋습니다.',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:37:00Z',
  },
  {
    id: 209,
    study_name: 'UI/UX 디자인',
    sender_id: 12,
    message_counter: 7,
    sender_nickname: '한지민',
    study_group_id: 108,
    content: '오늘 주제는 React Hooks입니다.',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:38:00Z',
  },
  {
    id: 210,
    study_name: '모바일 앱 개발',
    sender_id: 13,
    message_counter: 0,
    sender_nickname: '신동현',
    study_group_id: 109,
    content: '네, 기대됩니다!',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:39:00Z',
  },
  {
    id: 211,
    study_name: 'DevOps 자동화',
    sender_id: 14,
    message_counter: 1,
    sender_nickname: '오수민',
    study_group_id: 110,
    content: 'useEffect 사용 시 주의할 점은 무엇일까요?',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:40:00Z',
  },
  {
    id: 212,
    study_name: '인공지능 기초',
    sender_id: 15,
    message_counter: 0,
    sender_nickname: '구하준',
    study_group_id: 111,
    content: '의존성 배열을 잘 관리해야겠죠.',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:41:00Z',
  },
  {
    id: 213,
    study_name: '프론트엔드 성능',
    sender_id: 16,
    message_counter: 2,
    sender_nickname: '남지아',
    study_group_id: 112,
    content: '맞습니다. 클린업 함수도 중요하고요.',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:42:00Z',
  },
  {
    id: 214,
    study_name: '백엔드 보안',
    sender_id: 17,
    message_counter: 0,
    sender_nickname: '류준서',
    study_group_id: 113,
    content: 'useCallback, useMemo도 함께 사용하면 좋죠.',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:43:00Z',
  },
  {
    id: 215,
    study_name: '데이터 분석',
    sender_id: 18,
    message_counter: 9,
    sender_nickname: '문예린',
    study_group_id: 114,
    content: '네, 성능 최적화에 도움이 됩니다.',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:44:00Z',
  },
  {
    id: 216,
    study_name: '머신러닝 응용',
    sender_id: 19,
    message_counter: 0,
    sender_nickname: '박서준',
    study_group_id: 115,
    content: 'Zustand로 상태 관리하는 것도 편하더라고요.',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:45:00Z',
  },
  {
    id: 217,
    study_name: '블록체인 기초',
    sender_id: 20,
    message_counter: 4,
    sender_nickname: '서하윤',
    study_group_id: 116,
    content: '맞아요. TanStack Query도 비동기 데이터 관리에 최고죠.',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:46:00Z',
  },
  {
    id: 218,
    study_name: '게임 개발 입문',
    sender_id: 21,
    message_counter: 0,
    sender_nickname: '유지호',
    study_group_id: 117,
    content: '네, 캐싱 기능이 정말 유용합니다.',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:47:00Z',
  },
  {
    id: 219,
    study_name: '클린 코드 실천',
    sender_id: 22,
    message_counter: 11,
    sender_nickname: '이도윤',
    study_group_id: 118,
    content: '오늘 스터디 내용 정말 유익했습니다.',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:48:00Z',
  },
  {
    id: 220,
    study_name: '테스팅 전략',
    sender_id: 23,
    message_counter: 0,
    sender_nickname: '장예원',
    study_group_id: 119,
    content: '저도요! 감사합니다.',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:49:00Z',
  },
  {
    id: 221,
    study_name: '애자일 방법론',
    sender_id: 24,
    message_counter: 6,
    sender_nickname: '전하은',
    study_group_id: 120,
    content: '다음 주 주제는 무엇으로 할까요?',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:50:00Z',
  },
  {
    id: 222,
    study_name: '스크럼 마스터',
    sender_id: 25,
    message_counter: 0,
    sender_nickname: '조민준',
    study_group_id: 121,
    content: '음... Next.js 어떠세요?',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:51:00Z',
  },
  {
    id: 223,
    study_name: '프로젝트 관리 툴',
    sender_id: 26,
    message_counter: 1,
    sender_nickname: '차은우',
    study_group_id: 122,
    content: '좋은 생각입니다! Next.js로 SSR/SSG에 대해 다뤄볼까요?',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:52:00Z',
  },
  {
    id: 224,
    study_name: '커뮤니케이션 스킬',
    sender_id: 27,
    message_counter: 0,
    sender_nickname: '하윤서',
    study_group_id: 123,
    content: '네, 그렇게 하면 좋을 것 같아요.',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:53:00Z',
  },
  {
    id: 225,
    study_name: '리더십 개발',
    sender_id: 28,
    message_counter: 8,
    sender_nickname: '홍지훈',
    study_group_id: 124,
    content: '그럼 다음 주에 뵙겠습니다!',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:54:00Z',
  },
  {
    id: 226,
    study_name: '문제 해결 능력',
    sender_id: 29,
    message_counter: 0,
    sender_nickname: '황채원',
    study_group_id: 125,
    content: '수고하셨습니다!',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:55:00Z',
  },
  {
    id: 227,
    study_name: '비판적 사고 훈련',
    sender_id: 30,
    message_counter: 2,
    sender_nickname: '김도현',
    study_group_id: 126,
    content: '수고하셨습니다!',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:56:00Z',
  },
  {
    id: 228,
    study_name: '팀워크 향상',
    sender_id: 5,
    message_counter: 0,
    sender_nickname: '홍길동',
    study_group_id: 127,
    content: '오늘 저녁은 뭐 드세요?',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:57:00Z',
  },
  {
    id: 229,
    study_name: '프론트엔드 아키텍처',
    sender_id: 6,
    message_counter: 15,
    sender_nickname: '김철수',
    study_group_id: 128,
    content: '저는 치킨 먹으려고요!',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T10:58:00Z',
  },
  {
    id: 230,
    study_name: '백엔드 아키텍처',
    sender_id: 5,
    message_counter: 0,
    sender_nickname: '홍길동',
    study_group_id: 129,
    content: '오 저도 치킨 좋아하는데!',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T10:59:00Z',
  },
  {
    id: 231,
    study_name: '데이터베이스 최적화',
    sender_id: 6,
    message_counter: 3,
    sender_nickname: '김철수',
    study_group_id: 130,
    content: '같이 드실래요?',
    file_url: null,
    is_read: false,
    created_at: '2025-10-15T11:00:00Z',
  },
  {
    id: 232,
    study_name: '클라우드 보안',
    sender_id: 5,
    message_counter: 0,
    sender_nickname: '홍길동',
    study_group_id: 131,
    content: '좋아요! 어디서 만날까요?',
    file_url: null,
    is_read: true,
    created_at: '2025-10-15T11:01:00Z',
  },
]
